version: '3.8'
services:
  jira-ya-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - temp-sqlite-data:/app/TempDatabase.db

volumes:
  temp-sqlite-data:
